name: Build kube-fledged

on:
  push:
    tags:
      - 'v*'

jobs:
  push_tag:
    uses: ./.github/workflows/build-kube-fledged.yml
    with:
      alpine_version: 3.16.2
      crictl_version: v1.25.0
      docker_version: 20.10.20
      golang_version: 1.19.2
      operatorsdk_version: v1.24.1
      release_version: v0.10.0
      controller_image_repo: 425927401566.dkr.ecr.ap-northeast-1.amazonaws.com/kube-fledged-controller
      crictl_image_repo: 425927401566.dkr.ecr.ap-northeast-1.amazonaws.com/kube-fledged-cri-client
      dockerfile_controller: build/Dockerfile.controller
      dockerfile_cri_client: build/Dockerfile.cri_client
      dockerfile_operator: deploy/kubefledged-operator/build/Dockerfile
      dockerfile_webhook_server: build/Dockerfile.webhook_server
      operator_image_repo: 425927401566.dkr.ecr.ap-northeast-1.amazonaws.com/kube-fledged-operator
      operator_target_platforms: linux/amd64,linux/arm64
      push_image: true
      target_platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
      webhook_server_image_repo: 425927401566.dkr.ecr.ap-northeast-1.amazonaws.com/kube-fledged-webhook-server
